In [8]:
import pandas as pd
df = pd.read_csv(
    r"C:\Users\Bhadmus\Documents\online_retail_II.xlsx.csv",
    encoding='ISO-8859-1'
)
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,09-12-2011 12:50,18.00,12680.0,France

In [9]:
#Missing values
df.isnull().sum() #this shows the number of missing values in each column. There are about 135080 missing values in the Customer ID column and about 1454 missing values in the Description column.b
df['Customer ID'] = df['Customer ID'].fillna(0) #there were about 135080 missing values in the Customer ID column, I have filled them with 0 since it is a numeric column and it will not affect the analysis.
df['Customer ID'] = df['Customer ID'].astype(int)
df['Description'] = df['Description'].fillna('Unknown') #there were about 1454 missing values in the Description column, I have filled them with 'Unknown' since it is a categorical column and it will not affect the analysis.
df.isnull().sum()
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680,France
541909,581587,POST,POSTAGE,1,09-12-2011 12:50,18.00,12680,France

In [10]:
df['InvoiceDate']= df['InvoiceDate'].astype(str).str.strip() #this will remove any leading or trailing spaces from the InvoiceDate column and convert it to string type.
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'],dayfirst=True, format='mixed', errors='coerce') #this will convert the InvoiceDate column to datetime format. If there are any invalid date formats, they will be set to NaT (Not a Time).
df['InvoiceDate'].isnull().sum() #this will show the number of missing values
df['InvoiceDate'].dtype #this will show the data type of the InvoiceDate column, which should be datetime64[ns] after the conversion.
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France
541909,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680,France

In [11]:
df['Description'] = df['Description'].str.strip()
df['Description'] = df['Description'].str.lower()
df['Description'] = df['Description'].str.replace(' ', '_')
df['Country'] = df['Country'].str.strip()
df.duplicated().sum() #to check if there are any duplicated rows in the dataset after cleaning the Description and Country columns. This shows that there are no duplicated rows in the dataset.
# This shows EVERY row that has a twin somewhere else in the data
duplicates_to_inspect = df[df.duplicated(keep=False)].sort_values(by='Invoice')

# Display the first 10
duplicates_to_inspect

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
485,536409,22111,scottie_dog_hot_water_bottle,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
489,536409,22866,hand_warmer_scotty_dog_design,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
494,536409,21866,union_jack_flag_luggage_tag,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
517,536409,21866,union_jack_flag_luggage_tag,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
521,536409,22900,set_2_tea_towels_i_love_london,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
...,...,...,...,...,...,...,...,...
440149,C574510,22360,glass_jar_english_confectionery,-1,2011-11-04 13:25:00,2.95,15110,United Kingdom
461407,C575940,23309,set_of_60_i_love_london_cake_cases,-24,2011-11-13 11:38:00,0.55,17838,United Kingdom
461408,C575940,23309,set_of_60_i_love_london_cake_cases,-24,2011-11-13 11:38:00,0.55,17838,United Kingdom
529981,C580764,22667,recipe_box_retrospot,-12,2011-12-06 10:38:00,2.95,14562,United Kingdom
529980,C580764,22667,recipe_box_retrospot,-12,2011-12-06 10:38:00,2.95,14562,United Kingdom

In [12]:
df.drop_duplicates(inplace=True)#to remove any duplicated rows in the dataset after cleaning the Description and Country columns. This will ensure that there are no duplicated rows in the dataset
df['Revenue'] = df['Quantity'] * df['Price'] #this creates a new column called Revenue which is the product of Quantity and Price columns. This will be useful for analysis later on.
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,536365,85123A,white_hanging_heart_t-light_holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,white_metal_lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,cream_cupid_hearts_coat_hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,knitted_union_flag_hot_water_bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,red_woolly_hottie_white_heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541905,581587,22899,children's_apron_dolly_girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
541906,581587,23254,childrens_cutlery_dolly_girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541907,581587,23255,childrens_cutlery_circus_parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541908,581587,22138,baking_set_9_piece_retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85
541909,581587,POST,postage,1,2011-12-09 12:50:00,18.00,12680,France,18.00

In [14]:
df_customers = df[(df['Customer ID'] != 0) & (df['Description'] != 'Unknown')] #this creates a new dataframe called df_customers which only contains rows where the CustomerID is not 0 and the Description is not 'Unknown'. This will be useful for analysis later on since we want to focus on customers who have made purchases and have valid descriptions.
df_customers

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,536365,85123A,white_hanging_heart_t-light_holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,white_metal_lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,cream_cupid_hearts_coat_hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,knitted_union_flag_hot_water_bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,red_woolly_hottie_white_heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541905,581587,22899,children's_apron_dolly_girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
541906,581587,23254,childrens_cutlery_dolly_girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541907,581587,23255,childrens_cutlery_circus_parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541908,581587,22138,baking_set_9_piece_retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85
541909,581587,POST,postage,1,2011-12-09 12:50:00,18.00,12680,France,18.00

In [16]:
df_customers.columns = (df_customers
                        .columns
                      .str.strip() 
                      .str.replace(' ', '_')
                      ) #this cleans the column names by stripping any leading or trailing whitespace, converting them to lowercase, and replacing any spaces with underscores. This will make it easier to work with the column names in the analysis later on.

In [17]:
df_customers

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer_ID,Country,Revenue
0,536365,85123A,white_hanging_heart_t-light_holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,white_metal_lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,cream_cupid_hearts_coat_hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,knitted_union_flag_hot_water_bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,red_woolly_hottie_white_heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541905,581587,22899,children's_apron_dolly_girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
541906,581587,23254,childrens_cutlery_dolly_girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541907,581587,23255,childrens_cutlery_circus_parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
541908,581587,22138,baking_set_9_piece_retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85
541909,581587,POST,postage,1,2011-12-09 12:50:00,18.00,12680,France,18.00

In [18]:
df_customers.to_csv("cleaned_online_retail.csv", index=False)